[package]
name = "faster-beamer"
version = "0.1.0"
authors = ["Stephan Seitz <stephan.seitz@fau.de>"]
edition = "2018"

[dependencies]
tree-sitter = "0.3.7"
tera = "0.11"
serde_json = "1.0.38"
dirs = "1.0"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.2.0"
clap = "2.32.0"
hotwatch = "0.3.1"
log = "0.4"
pretty_env_logger = "0.3.0"
tectonic = "0.1.11"
latexcompile = "0.1.0"
lopdf = "0.20.0"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
