[package]
name = "faster-beamer"
version = "0.1.0"
authors = ["Stephan Seitz <stephan.seitz@fau.de>"]
edition = "2018"
description = "An incremental compiler for LaTeX Beamer slides"
license="GPLv3"
repository = "https://github.com/theHamsta/faster-beamer"
keywords = ["latex"]
homepage = "https://github.com/theHamsta/faster-beamer"
categories = ["Latex"]
readme = "README.md"
license-file = "LICENSE"
license = "GPLv3"

[dependencies]
tree-sitter = "0.3.10"
serde_json = "1.0.41"
dirs = "2.0.2"
serde = { version = "1.0.101", features = ["derive"] }
lazy_static = "1.4.0"
clap = "2.33.0"
hotwatch = "0.4.2"
log = { version = "0.4.8", features = ["max_level_debug", "release_max_level_warn"] }
pretty_env_logger = "0.3.1"
latexcompile = { git = "https://github.com/theHamsta/latexcompile" }
cachedir = "0.1.1"
md5 = "0.6.1"
rayon = "1.2.0"
regex = "1.3.1"
symlink = "0.1.0"

[build-dependencies]
cc = { version = "1.0.45", features = ["parallel"] }
